name: invoiso
description: "Invoice generating desktop app built with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.11.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.0.15
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  csv: ^6.0.0
  open_file: ^3.3.2
  url_launcher: ^6.2.6
  downloads_path_provider_28: any
  syncfusion_flutter_pdfviewer: ^30.1.40
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  flutter_svg: ^2.0.10+1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_rename: ^1.10.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/logo.png
   - assets/images/logo.svg
   - assets/templates/classic.png
   - assets/templates/modern.png
   - assets/templates/minimal.png

package_rename_config:
  linux:
    app_name: invoiso
    package_name: invoiso
    exe_name: invoiso

  windows:
    app_name: invoiso
    organization: anoopp
    copyright_notice: Copyright ©️ 2025 anoopp. All rights reserved.
    exe_name: invoiso

  web:
    app_name: invoiso
    short_app_name: invoiso
    description: Invoice generating desktop app built with Flutter